model ETAFactorySimulationLib_ProductionSystems_CleaningMachines_Test_Test_ThroughputCleaningSystem_Frank
 extends ETAFactorySimulationLib.ProductionSystems.CleaningMachines.Test.Test_ThroughputCleaningSystem_Frank;
  annotation(experiment(StopTime=10000, __Dymola_Algorithm="Dassl"),uses(ETAFactorySimulationLib(version="0.2")));
end ETAFactorySimulationLib_ProductionSystems_CleaningMachines_Test_Test_ThroughputCleaningSystem_Frank;
